server:
  port: 9999

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:112.74.20.204}:${NACOS_PORT:8848}
      config:
        server-addr: http://112.74.20.204:8848
  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  profiles:
    active: @profiles.active@



